apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: auckland-shop
  region: ap-southeast-2
nodeGroups:
   - name: ng1
     desiredCapacity: 1
     instanceType: t2.micro
   - name: ng-mixed
     minSize: 1
     maxSize: 1
     instancesDistribution:
       maxPrice: 0.010
       instanceTypes: ["t2.micro"] # At least one instance type should be specified
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 1    
     